### PR TITLE
drop ha and ceph repocheck in favor of nodes repocheck

### PR DESCRIPTION
**Pull request by MaximilianMeister**
depends on https://github.com/crowbar/crowbar-core/pull/644

### CODE REVIEW

**Comment by jsuchome** [comment]
+1

**Comment by MaximilianMeister** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ncdOGOzP&#x2F;97-3-s47p11-implement-api-for-repo-checks-during-upgrade-upgrade-step-8"> (3) S47P11 Implement API for repo checks during upgrade (upgrade step 8)</a>

**Comment by rsalevsky** [comment]
Can you give an example how the output looks like?

**Comment by MaximilianMeister** [comment]
> Can you give an example how the output looks like?

@rsalevsky
```ruby
➜  crowbar_framework git:(upgrade/node-repocheck) ✗ crowbarctl upgrade repocheck nodes
+---------------------------------------+--------------------------------+
| Status                                | Value                          |
+---------------------------------------+--------------------------------+
| ceph.available                        | false                          |
| ha.available                          | false                          |
| os.available                          | true                           |
| openstack.available                   | false                          |
| openstack.repos.missing_repos.x86_64  | SUSE-OpenStack-Cloud-7-Pool    |
|                                       | SUSE-OpenStack-Cloud-7-Updates |
| openstack.repos.inactive_repos.x86_64 | SUSE-OpenStack-Cloud-7-Pool    |
|                                       | SUSE-OpenStack-Cloud-7-Updates |
+---------------------------------------+--------------------------------+
➜  crowbar_framework git:(upgrade/node-repocheck) ✗ crowbarctl upgrade repocheck nodes --format json
{
  "ceph": {
    "available": false,
    "repos": {
    }
  },
  "ha": {
    "available": false,
    "repos": {
    }
  },
  "os": {
    "available": true,
    "repos": {
    }
  },
  "openstack": {
    "available": false,
    "repos": {
      "missing_repos": {
        "x86_64": [
          "SUSE-OpenStack-Cloud-7-Pool",
          "SUSE-OpenStack-Cloud-7-Updates"
        ]
      },
      "inactive_repos": {
        "x86_64": [
          "SUSE-OpenStack-Cloud-7-Pool",
          "SUSE-OpenStack-Cloud-7-Updates"
        ]
      }
    }
  }
}
```

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
