### PR TITLE
Node subcommand improvements

### PR DESCRIPTION
**Pull request by tboerger**
* Drop no-alias, no-name option from node list
* Added more columns to node list output
* Added option to hide meta data on node list
* Added group subcommand for nodes

~~**This pull request depends on https://github.com/crowbar/crowbar-core/pull/183 and 
https://github.com/crowbar/crowbar-core/pull/184**~~

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Don't we need a way to have just a list of names? Without meta, we still get the alias...

**Comment by tboerger** [comment]
> Don't we need a way to have just a list of names? Without meta, we still get the alias...

And where do we need that? :)

**Comment by tboerger** [comment]
```
# bundle exec bin/crowbarctl node list --no-meta --plain
crowbar.l6.cloud.suse.de
d52-54-77-77-77-01.l6.cloud.suse.de
d52-54-77-77-77-02.l6.cloud.suse.de
d52-54-77-77-77-03.l6.cloud.suse.de
d52-54-77-77-77-04.l6.cloud.suse.de
```

```
# bundle exec bin/crowbarctl node list --no-meta
+-------------------------------------+
| Name                                |
+-------------------------------------+
| crowbar.l6.cloud.suse.de            |
| d52-54-77-77-77-01.l6.cloud.suse.de |
| d52-54-77-77-77-02.l6.cloud.suse.de |
| d52-54-77-77-77-03.l6.cloud.suse.de |
| d52-54-77-77-77-04.l6.cloud.suse.de |
+-------------------------------------+
```

```
# bundle exec bin/crowbarctl node list --plain
crowbar.l6.cloud.suse.de crowbar sw-unknown ready
d52-54-77-77-77-01.l6.cloud.suse.de d52-54-77-77-77-01 sw-unknown ready
d52-54-77-77-77-02.l6.cloud.suse.de d52-54-77-77-77-02 sw-unknown ready
d52-54-77-77-77-03.l6.cloud.suse.de d52-54-77-77-77-03 sw-unknown ready
d52-54-77-77-77-04.l6.cloud.suse.de d52-54-77-77-77-04 sw-unknown ready
```

```
# bundle exec bin/crowbarctl node list
+-------------------------------------+--------------------+------------+--------+
| Name                                | Alias              | Group      | Status |
+-------------------------------------+--------------------+------------+--------+
| crowbar.l6.cloud.suse.de            | crowbar            | sw-unknown | ready  |
| d52-54-77-77-77-01.l6.cloud.suse.de | d52-54-77-77-77-01 | sw-unknown | ready  |
| d52-54-77-77-77-02.l6.cloud.suse.de | d52-54-77-77-77-02 | sw-unknown | ready  |
| d52-54-77-77-77-03.l6.cloud.suse.de | d52-54-77-77-77-03 | sw-unknown | ready  |
| d52-54-77-77-77-04.l6.cloud.suse.de | d52-54-77-77-77-04 | sw-unknown | ready  |
+-------------------------------------+--------------------+------------+--------+
```

**Comment by vuntz** [comment]
+1

**Pull request merged**
