### PR TITLE
upgrade: Enable querying the nodes upgrade status

### PR DESCRIPTION
**Pull request by MaximilianMeister**
## depends on
https://github.com/crowbar/crowbar-core/pull/1062

## example output
```bash
➜  ✗ crowbarctl upgrade status nodes 
+--------------+---------------------------------+
| Status       | Value                           |
+--------------+---------------------------------+
| upgraded     |                                 |
| not_upgraded | d52-54-77-77-77-03.emil.suse.de |
|              | d52-54-77-77-77-01.emil.suse.de |
|              | d52-54-77-77-77-02.emil.suse.de |
|              | d52-54-77-77-77-04.emil.suse.de |
+--------------+---------------------------------+
```

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
[(5) Allow user to choose which compute nodes to upgrade](https://trello.com/c/IZ8W5tQz/224-5-allow-user-to-choose-which-compute-nodes-to-upgrade)

**Comment by jsuchome** [comment]
Admin node IMHO should not be there, but that's a case for https://github.com/crowbar/crowbar-core/pull/1062

**Comment by jsuchome** [comment]
Could we show "Not Upgraded/Upgraded" instead of using the keys from the response (not_upgraded/upgrade) ?

**Comment by MaximilianMeister** [comment]
> Could we show "Not Upgraded/Upgraded" instead of using the keys from the response (not_upgraded/upgrade) ?

hmm then we'd have to write some custom formatter, but usually the key/value format is preferred as we have it in all the other outputs as well. so i'd prefer to not do it different here.

**Pull request merged**
