### PR TITLE
add subcommand to set up the crowbar db during the upgrade

### PR DESCRIPTION
**Pull request by MaximilianMeister**
depends on: https://github.com/crowbar/crowbar-init/pull/33

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;moLhQhOr&#x2F;100-3-add-crowbarctl-support-for-crowbar-init-upgrade-subcommand"> (3) Add crowbarctl support for crowbar init (upgrade subcommand)</a>

**Comment by rsalevsky** [comment]
For the hound issues see: https://github.com/crowbar/crowbar-client/pull/106

**Comment by rsalevsky** [comment]
Do we want to add the validation here?

**Comment by MaximilianMeister** [comment]
> Do we want to add the validation here?

I could create a new mixin for the database parameter validation

**Comment by rsalevsky** [comment]
+1

**Comment by Itxaka** [comment]
looks good +1

**Pull request merged**
