### PR TITLE
Switched to httmultiparty for allowing file uploads

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by aplanas** [comment]
+1 for the intention, but not knowledge enough to be sure that some change in the API will not break something

**Comment by tboerger** [comment]
> +1 for the intention, but not knowledge enough to be sure that some change in the API will not break something

I don't understand. It's just a wrapper around HTTParty that allows file uploads, which is a hard requirement for us. For our API we are building specs :)

**Comment by aplanas** [comment]
@tboerger well, you are replacing httparty with httmultiparty, as I see in the source code httmultiparty requires the old one, so I expect that both libraries provide the same API to our code, but this is the point where I am not sure. But if the gating is green this must be the case.

Still +1

**Comment by MaximilianMeister** [comment]
@tboerger can I merge this? or is the `do not merge yet` label still accurate? btw I have successfully tested it with https://github.com/crowbar/crowbar-client/pull/49

**Comment by MaximilianMeister** [comment]
:+1:

**Comment by tboerger** [comment]
The pull requests that use httpmultiparty are are all blocked until we get this rubygem for the SUSE cloud approvaed by legal department.

**Comment by rsalevsky** [comment]
@tboerger I think the SR is approved.

**Pull request merged**
