### PR TITLE
Fixed the help output for nested subcommands

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Fix for https://github.com/crowbar/crowbar-client/issues/58

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
screenshot from 2016-01-27 12-26-45

**Comment by tboerger** [comment]
screenshot from 2016-01-27 15-13-52

**Comment by MaximilianMeister** [comment]
+1

**Pull request merged**
