### PR TITLE
upgrade: Fix the "Next step" hint after removing database step

### PR DESCRIPTION
**Pull request by jsuchome**
Database step was removed completely, next step after admin upgrade
is repository check for nodes.

**REQUIRES**  https://github.com/crowbar/crowbar-client/pull/177

### CODE REVIEW

**Comment by jsuchome** [comment]
Do you think we should branch, or would it make sense to check the current product inside the code?

**Comment by skazi0** [comment]
To be honest I think we should do it inside the code if possible. Crowbar-client is released as a gem and I have no idea how versioning of these works :o)

**Comment by jsuchome** [comment]
@rsalevsky any idea? Branch crowbar-client or find out about the version internally?
(There's also https://github.com/crowbar/crowbar-client/pull/174)

**Comment by jsuchome** [comment]
@skazi0 don't I get it, or do you mean that client would need to do explicit call for status before realizing which upgrade is it serving?

**Comment by skazi0** [comment]
@jsuchome ah, you're right. We would need an additional call to status API. Another option is to add some version info to all responses. This way when calling the admin upgrade API we will get response with some info about what hint to display.

**Comment by jsuchome** [comment]
@skazi0 what about ENV variables? 
Like in https://github.com/crowbar/crowbar-client/blob/master/lib/crowbar/client/config.rb

Something like:
 - `ENV["CROWBAR_UPGRADE_VERSION"]` is present, use it (and that need to be set manually be remote users
 - otherwise check for `/var/lib/crowbar/upgrade/*-progress.yml` file to determine the version

**Comment by jsuchome** [comment]
@s-t-e-v-e-n-k not really. crowbar-client does not have any branches - that's the reason I'm coming up with solution involving https://github.com/crowbar/crowbar-client/pull/177 , otherwise I'd just put different code in different branches...

**Pull request merged**
