### PR TITLE
Refactoring and adding specs

### PR DESCRIPTION
**Pull request by tboerger**
* [x] Refactor the command registration
* [x] Refactor the request registration
* [x] Write specs for utils
* [x] Write specs for filters
* [x] Write specs for formatters
* [x] Write specs for requests
* [ ] ~~Write specs for commands~~ => https://github.com/crowbar/crowbar-client/issues/18
* [ ] ~~Write specs for the CLI calls~~ => https://github.com/crowbar/crowbar-client/issues/19

### CODE REVIEW

**Comment by vuntz** [comment]
Cool stuff, thanks for doing that!

(not doing a full review yet as I see it's still wip, but LGTM after a quick look)

**Comment by tboerger** [comment]
> Cool stuff, thanks for doing that!
> 
> (not doing a full review yet as I see it's still wip, but LGTM after a quick look)

Thanks, still enough left to refactor and test :)
I will ping you when it's good to review.

**Comment by tboerger** [comment]
I want to merge this PR for now. Than I will do followup pull requests for specs on command classes and cli calls itself.

**Comment by tboerger** [comment]
I will merge it now as I'm the only person working with it yet. The code will be hopefully readable enough. I have already created an issue to write proper yard documentation to make the architecture even more obvious.

**Pull request merged**
