### PR TITLE
fix bsc#993445

### PR DESCRIPTION
**Pull request by MaximilianMeister**
the command output from repository list was broken
repositories couldn't be (de)activated

https://bugzilla.suse.com/show_bug.cgi?id=993445

### CODE REVIEW

**Comment by rsalevsky** [comment]
Can you explain the change in the commit message a little bit more? Maybe `Fix repository handling (bsc#993445)`?

**Comment by MaximilianMeister** [comment]
> Can you explain the change in the commit message a little bit more? Maybe Fix repository handling (bsc#993445)?

done

**Comment by rsalevsky** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
