### PR TITLE
add sanity check subcommands to server subcommand

### PR DESCRIPTION
**Pull request by MaximilianMeister**
* check
* status

depends on https://github.com/crowbar/crowbar-core/pull/386

sanity-cli

### CODE REVIEW

**Comment by tboerger** [comment]
Do we really need different commands for that? Otherwise :+1:

**Comment by MaximilianMeister** [comment]
> Do we really need different commands for that?

it could also be fine to just always perform the check and return the result. then we wouldn't need subfolders either, just a check command. 

I leave it up to you if anyone has an opinion please share.
keep in mind that we may add more checks (other than network) in the future, which could require even a subcommand to the check subcommand (if we want to just run single checks)

**Comment by tboerger** [comment]
i think `crowbarctl server sanity` or `crowbarctl server check` should be fine for now.

**Comment by rsalevsky** [comment]
+1

**Comment by rsalevsky** [comment]
I agree with @tboerger just one command would be better for now.

**Comment by MaximilianMeister** [comment]
@tboerger how would you do the implementation then? AFAICS we would either need to:
* add another API endpoint which performs the check **and** returns the result

or

* for **one** subcommand use **two** request, which I am not sure of how  that fits into the architecture.

**Comment by MaximilianMeister** [comment]
> add another API endpoint which performs the check and returns the result

or I can just return the cached value in the `check` controller action, that would work

**Comment by tboerger** [comment]
Just use a single request.

**Comment by MaximilianMeister** [comment]
@tboerger done. https://github.com/crowbar/crowbar-core/pull/386/commits/d7c392768dd90a0798059316f379fc39956d7784 enables checking and parsing the result with a single request from here

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
thanks for merging, but better would have been to wait until the API is there, https://github.com/crowbar/crowbar-core/pull/386 is not merged yet. (but hopefully soon)

**Comment by tboerger** [comment]
@MaximilianMeister I'm not rolling a new gem yet, so nothing really bad for that.

**Comment by MaximilianMeister** [comment]
> I'm not rolling a new gem yet, so nothing really bad for that.

okay, i guess the dependent PR will be merged today anyways, so sorry for the noise

**Pull request merged**
