### PR TITLE
Discovered some bugs, important fixes!

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by aplanas** [comment]
Tests fails in `Crowbar::Client::Request::VirtualIP::Deallocate`, maybe needs to be updated the tests, or are fair fails?

**Comment by tboerger** [comment]
> Tests fails in Crowbar::Client::Request::VirtualIP::Deallocate, maybe needs to be updated the tests, or are fair fails?

Fixed the specs now, just used wrong parameters.

**Comment by aplanas** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
looks good, one typo in the commit message "correctl", and maybe you could squash the last one

**Pull request merged**
