### PR TITLE
rest-client: use the correct api response in case of an error

### PR DESCRIPTION
**Pull request by MaximilianMeister**
e.message only displays the http error formatted as a string
r.response actually contains the response body

see http://www.rubydoc.info/gems/rest-client/RestClient/Exception

### CODE REVIEW

**Comment by jsuchome** [comment]
could we format the output somehow?

```
root@crowbar:~ # crowbarctl upgrade repocheck nodes --format plain
{"errors":{"nodes_repo_checks":{"data":"Start of step nodes_repo_checks requested in the wrong order","help":"Refer to the error message in the response"}}}
root@crowbar:~ # crowbarctl upgrade repocheck nodes --format json
{
  "error": "{\"errors\":{\"nodes_repo_checks\":{\"data\":\"Start of step nodes_repo_checks requested in the wrong order\",\"help\":\"Refer to the error message in the response\"}}}"
}
```

**Comment by MaximilianMeister** [comment]
> could we format the output somehow?

yes we could, but this requires some extra effort, as it is not that trivial. we can have different json structures returned by the api on different endpoints, and here in this case we would need only the `data` and the `help` message. i guess if we want to correctly format it, we would have to consider every subcommand, and add code to the `command` class to format the output correctly.

I'd do this as a next step, i can create a card for that. for now we'd at least have some useful error message, but i agree the format is not really good now

**Comment by MaximilianMeister** [comment]
e.g. in https://github.com/crowbar/crowbar-client/blob/master/lib/crowbar/client/command/upgrade/repocheck.rb#L53 it would look like:

```ruby
err JSON.parse(request.parsed_response["error"].body)["errors"]["admin_repo_checks"]["data"]
```

**Comment by MaximilianMeister** [comment]
we could implement some Mixin that does the formatting, at least for the upgrade subcommands that have this specific response structure

**Comment by jsuchome** [comment]
Well, we have some table formatting, e.g. for `upgrade status` or `upgrade prechecks`. As crowbarctl is command line tool, I do not see why it should have return the json structure on error.

**Comment by MaximilianMeister** [comment]
> Well, we have some table formatting, e.g. for upgrade status or upgrade prechecks. As crowbarctl is command line tool, I do not see why it should have return the json structure on error.

yes, but for every table we have custom formatting logic too, and this is different for every subcommand. so it means some work (and becoming strictly dependent on server response structures). and as I mentioned in my example above I can just print out the actual error message (`data`), the important bit.

**Comment by jsuchome** [comment]
OK, let's leave it as it is and solve it generically in next sprint. +1

**Comment by jsuchome** [comment]
@rsalevsky @Itxaka apparently this repository still requires +1's

**Comment by MaximilianMeister** [comment]
> OK, let's leave it as it is and solve it generically in next sprint.

I have added it already, as we need to make a rubygem release relatively soon, along with some other changes. now it looks like:

```bash
➜  crowbar-client git:(error-response) ✗ crowbarctl upgrade repocheck crowbar
Start of step admin_repo_checks requested in the wrong order
```

**Pull request merged**
